### ISSUE TITLE
Improve the exercise!

### ISSUE THREAD

**Issue by nasivuela** [Adalab/e-s3-evaluacion-intermedia-inmasalcedo#1]
Well done @inmasalcedo  !

Some tips to improve it:

- [x] Move `li` outside 'Pokemon' component, this way it is a simple card that we can use anywhere not only inside a `ul`
- [x] Add title of the page (Mi lista de Pokemons)
- [x] Use `id` of pokemon for the `key` of React when mapping
- [x] Add styles (one file per component)
- [x] Use propTypes to check your props
- [x] Review metadata on index.html (lang, title...)
- [x] Clean and indent
- [ ] Publish on Github Pages

When working on small projects maybe git-flow adds more complexity than needed. But if you use it, do not forget to merge into master ;)

Go for it!

**Comment by inmasalcedo** [comment]
Hi!
Thanks for the feedback! I followed your instructions and I improve my intermediate evaluation. 
If you can take a look for further improvements I'll be glad to modify it :)

**Comment by nasivuela** [comment]
Good work @inmasalcedo!

![](https://media.giphy.com/media/yyZRSvISN1vvW/giphy.gif)

Make sure it is published on GP.
